version: "3"

services:
  app:
    build:
      args:
        user: $USER
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: webservices-api
    container_name: php_webservices
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      
  db:
    image: postgres:9.6-alpine
    restart: unless-stopped
    container_name: db_webservices
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      PGUSER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: posgres
    volumes:   
        - ./docker-compose/postgres:/docker-entrypoint-initdb.d
  nginx:
    image: nginx:alpine
    container_name: nginx_webservices
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/

